# Generated by Django 4.1.7 on 2023-03-05 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_remove_rent_id_remove_sell_id_rent_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='file_id',
        ),
        migrations.AddField(
            model_name='rent',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='id',
            field=models.PositiveBigIntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
