# Generated by Django 4.1.7 on 2023-03-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_remove_rent_file_id_remove_sell_file_id_rent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='file_id',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sell',
            name='file_id',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
