# Generated by Django 4.1.7 on 2023-03-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_remove_rent_file_id_remove_sell_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='owner_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rent',
            name='owner_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='sell',
            name='owner_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sell',
            name='owner_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='sell',
            name='type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین'), ('S', 'مغازه'), ('H', 'خانه و ویلا')], default='A', max_length=1),
        ),
    ]
