# Generated by Django 4.1.7 on 2023-03-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0014_alter_rent_owner_name_alter_rent_owner_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='tags',
            new_name='tag_manager',
        ),
    ]
