# Generated by Django 4.1.7 on 2023-03-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_profile_rent_files_and_more'),
        ('file', '0015_rename_tags_sell_tag_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='tags',
            new_name='tags_manager',
        ),
        migrations.AddField(
            model_name='rent',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.profile', verbose_name='added to site by '),
        ),
        migrations.AddField(
            model_name='sell',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents.profile', verbose_name='added to site by '),
        ),
    ]
