# Generated by Django 4.1.7 on 2023-03-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
