# Generated by Django 4.1.7 on 2023-03-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0019_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='agents_m.profile', verbose_name="user's profile"),
        ),
    ]
