# Generated by Django 4.1.7 on 2023-03-21 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0021_alter_comment_user_alter_rent_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by '),
        ),
        migrations.AlterField(
            model_name='sell',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by '),
        ),
    ]
