# Generated by Django 4.1.7 on 2023-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0031_alter_rent_options_alter_sell_options_sellimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='image5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
