# Generated by Django 4.1.7 on 2023-05-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0038_sellcomment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='bazdid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='bedroom',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='komod_divari',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='parking_motor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='tabaghat',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='tabdil',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='takhlie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rent',
            name='vahedha',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='bazdid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sell',
            name='bedroom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='komod_divari',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='parking_motor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='tabaghat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='takhlie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sell',
            name='vahedha',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
    ]
