# Generated by Django 4.1.7 on 2023-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0039_rent_bazdid_rent_bedroom_rent_komod_divari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='takhlie',
            field=models.CharField(max_length=100),
        ),
    ]
