# Generated by Django 4.1.7 on 2023-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0040_alter_rent_takhlie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='bazdid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='takhlie',
            field=models.CharField(max_length=100),
        ),
    ]
