# Generated by Django 4.1.7 on 2023-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0041_alter_sell_bazdid_alter_sell_takhlie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='bazdid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='komod_divari',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='parking_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tabaghat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tabdil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='takhlie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='vahedha',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bazdid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='komod_divari',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sell',
            name='parking_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sell',
            name='tabaghat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='takhlie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='vahedha',
            field=models.IntegerField(null=True),
        ),
    ]
