# Generated by Django 4.1.7 on 2023-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0044_alter_rent_price_rent_alter_rent_price_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price_up',
            field=models.IntegerField(),
        ),
    ]
