# Generated by Django 4.1.7 on 2023-08-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0046_rename_type_rent_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='divar_token',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='divar_token',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
