# Generated by Django 4.1.7 on 2023-08-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0047_rent_tenet_name_rent_tenet_phone_sell_tenet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='m2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
