# Generated by Django 4.1.7 on 2023-08-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0050_alter_rent_status_alter_sell_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
