# Generated by Django 4.1.7 on 2023-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0051_merge_20230822_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='tabdil',
            field=models.IntegerField(),
        ),
    ]
