# Generated by Django 4.1.7 on 2023-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0052_alter_rent_tabdil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='tabdil',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
