# Generated by Django 4.1.7 on 2023-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0014_buycustomer_status_rentcustomer_status"),
        ("file", "0054_rent_notified_customers_sell_notified_customers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rent",
            name="notified_customers",
        ),
        migrations.RemoveField(
            model_name="sell",
            name="notified_customers",
        ),
        migrations.AddField(
            model_name="rent",
            name="notified_customers",
            field=models.ManyToManyField(to="customer.buycustomer"),
        ),
        migrations.AddField(
            model_name="sell",
            name="notified_customers",
            field=models.ManyToManyField(to="customer.buycustomer"),
        ),
    ]
