# Generated by Django 4.1.7 on 2023-03-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_buycustomer_type_rentcustomer_type'),
        ('file', '0015_rename_tags_sell_tag_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=12)),
                ('rent_files', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file.rent', verbose_name='rent files')),
                ('sell_customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.rentcustomer', verbose_name='rent customer')),
                ('sell_files', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file.sell', verbose_name='sell files')),
            ],
        ),
    ]
