# Generated by Django 4.1.7 on 2023-03-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_buycustomer_type_rentcustomer_type'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rent_customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.rentcustomer', verbose_name='rent customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='sell_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.buycustomer', verbose_name='buy customer'),
        ),
    ]
