# Generated by Django 4.1.7 on 2023-03-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_profile_rent_customer_alter_profile_sell_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rent_customer',
        ),
    ]
