# Generated by Django 4.1.7 on 2023-03-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_profile_rent_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rent_files',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sell_customer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sell_files',
        ),
    ]
