version: "1"
services:
  postgres:
    image: postgres:15.4
    container_name: database
    environment:
      POSTGRES_USER: amlak
      POSTGRES_PASSWORD: amlak
      POSTGRES_DB: amlak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
