services:
  postgres:
    image: postgres:15.4
    container_name: database
    environment:
      POSTGRES_USER: amlak
      POSTGRES_PASSWORD: amlak
      POSTGRES_DB: amlak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - komak-moshaver

    restart: always
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
        - komak-moshaver
  frontend:
    build: ./front-end/
    ports:
      - "3000:5173"
    env_file:
      - ./front-end/.env
    depends_on:
      - backend
    networks:
        - komak-moshaver

networks:
  komak-moshaver:
volumes:
  postgres_data:
