services:
  postgres:
    image: docker.arvancloud.ir/postgres:15.4
    container_name: postgres
    environment:
      POSTGRES_USER: amlak
      POSTGRES_PASSWORD: amlak
      POSTGRES_DB: amlak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - komak-moshaver
    restart: unless-stopped 

  backend:
    build:
      context: ./backend/
      target: prod
    environment:
      #TODO: these need to be in a .env file
      DEBUG: "True"
      SECRET_KEY: "!88(h4((q=skn3flqv%cmdhx2-3#6l%1_$il@m#l)3t^l#g+5a"
      DB_NAME: "amlak"
      DB_HOST: postgres
      DB_USER: "amlak"
      DB_PASS: "amlak"
      DB_PORT: "5432"
      LIARA_ENDPOINT: "https://storage.iran.liara.space  "
      LIARA_BUCKET_NAME: "komak-moshaver-cdn"
      LIARA_ACCESS_KEY: "iec9uco4ckoq6f54"
      LIARA_SECRET_KEY: "ce4dd301-f94f-4b83-8096-7682ea5184c7"
      NESHAN_STATIC_MAP_API: "service.db7794d6a5ee46579d1a433d0115958e"
      NESHAN_SERVICES_API: "service.c5332c5dc61c41d083e7b5bc438889ee"
      LOCATIONS_MEDIA_DIR: "/usr/share/nginx/html/media/"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - media_data:/usr/share/nginx/html/media/
    networks:
      - komak-moshaver
    restart: unless-stopped 

  nginx:
    build:
      context: ./front-end/
      target: prod
    ports:
      - "80:80"
    environment:
      VITE_API: "/api/"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_data:/usr/share/nginx/html/media/
    networks:
      - komak-moshaver
    restart: unless-stopped 


networks:
  komak-moshaver:

volumes:
  postgres_data:
  media_data:
