
services:
  postgres:
    image: postgres:15.4
    container_name: database
    environment:
      POSTGRES_USER: amlak
      POSTGRES_PASSWORD: amlak
      POSTGRES_DB: amlak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - komak-moshaver

  backend:
    build:
      context: ./backend/
      target: prod  # Specify production target from Dockerfile
    environment:
      DEBUG: "False"
      SECRET_KEY: "!88(h4((q=skn3flqv%cmdhx2-3#6l%1_$il@m#l)3t^l#g+5a"
      DB_NAME: "amlak"
      DB_HOST: "database"
      DB_USER: "amlak"
      DB_PASS: "amlak"
      DB_PORT: "5432"
      LIARA_ENDPOINT: "https://storage.iran.liara.space"
      LIARA_BUCKET_NAME: "komak-moshaver-cdn"
      LIARA_ACCESS_KEY: "iec9uco4ckoq6f54"
      LIARA_SECRET_KEY: "ce4dd301-f94f-4b83-8096-7682ea5184c7"
    ports:
      - "8000:8000"  
    depends_on:
      - postgres 
    networks:
      - komak-moshaver

  frontend:
    build:
      context: ./front-end/
      target: prod  # Specify production target from Dockerfile
    ports:
      - "80:80" 
    environment:
      VITE_API: "/api/"
    depends_on:
      - backend 
    networks:
      - komak-moshaver

  redis:
    image: redis:latest  # Use the latest Redis image
    ports:
      - "6379:6379"  # Expose Redis port
    networks:
      - komak-moshaver 

  celery:
    build:
      context: ./backend/
      target: prod
    command: celery -A amlak worker -l info
    volumes:
      - ./backend/:/app
    depends_on:
      - backend
      - redis
    networks:
        - komak-moshaver
    environment:
      DJANGO_SETTINGS_MODULE: amlak.settings
      DEBUG: "False" 
      SECRET_KEY: "someSecretKey$" 
      DB_NAME: "amlak"
      DB_HOST: postgres
      DB_USER: "amlak"
      DB_PASS: "amlak"
      DB_PORT: 5432
      CELERY_BROKER_URL: "redis://redis:6379/0"  # Set Redis as the broker
networks:
  komak-moshaver:

volumes:
  postgres_data:
