# Generated by Django 4.1.6 on 2023-02-20 16:22

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0001_initial'),  # Add this dependency
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('m2', models.IntegerField()),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('elevator', models.BooleanField(default=True)),
                ('storage', models.BooleanField(default=True)),
                ('parking', models.BooleanField()),
                ('type', models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین'), ('S', 'مغازه')], default='A', max_length=1)),
                ('tags', taggit.managers.TaggableManager(
                    help_text='A comma-separated list of tags.',
                    through='taggit.TaggedItem',  # Keep as string or change to actual model reference
                    to='taggit.Tag',
                    verbose_name='Tags'
                )),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('m2', models.IntegerField()),
                ('price_up', models.IntegerField()),
                ('price_rent', models.IntegerField()),
                ('year', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('elevator', models.BooleanField(default=True)),
                ('storage', models.BooleanField(default=True)),
                ('parking', models.BooleanField()),
                ('type', models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین'), ('S', 'مغازه')], default='A', max_length=1)),
                ('tags', taggit.managers.TaggableManager(
                    help_text='A comma-separated list of tags.',
                    through='taggit.TaggedItem',  # Keep as string or change to actual model reference
                    to='taggit.Tag',
                    verbose_name='Tags'
                )),
            ],
        ),
    ]
