# Generated by Django 4.1.7 on 2023-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_sell_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='type',
            field=models.CharField(choices=[('آپارتمان', 'A'), ('زمین', 'L'), ('مغازه', 'S')], default='آپارتمان', max_length=8),
        ),
    ]
