# Generated by Django 4.1.7 on 2023-03-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_alter_rent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='type',
            field=models.CharField(choices=[('آپارتمان', 'Apartemant'), ('زمین', 'Land'), ('مغازه', 'Store')], default='آپارتمان', max_length=8),
        ),
        migrations.AlterField(
            model_name='sell',
            name='type',
            field=models.CharField(choices=[('آپارتمان', 'Apartemant'), ('زمین', 'Land'), ('مغازه', 'Store')], default='آپارتمان', max_length=8),
        ),
    ]
