# Generated by Django 4.1.7 on 2023-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_rent_type_alter_sell_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین'), ('S', 'مغازه')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='sell',
            name='type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین'), ('S', 'مغازه')], default='A', max_length=1),
        ),
    ]
