# Generated by Django 4.1.7 on 2023-03-05 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_alter_rent_type_alter_sell_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='id',
        ),
        migrations.AddField(
            model_name='rent',
            name='file_id',
            field=models.PositiveBigIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sell',
            name='file_id',
            field=models.PositiveBigIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
