# Generated by Django 4.1.7 on 2023-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_alter_rent_id_alter_sell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='file_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='file_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
