# Generated by Django 4.1.7 on 2023-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_alter_rent_file_id_alter_sell_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='file_id',
            field=models.PositiveBigIntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='file_id',
            field=models.PositiveBigIntegerField(auto_created=True),
        ),
    ]
