# Generated by Django 4.1.7 on 2023-03-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_alter_rent_file_id_alter_sell_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='file_id',
        ),
    ]
