# Generated by Django 4.1.7 on 2023-03-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0016_rename_tags_rent_tags_manager_rent_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents_m.profile', verbose_name='added to site by '),
        ),
        migrations.AlterField(
            model_name='sell',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents_m.profile', verbose_name='added to site by '),
        ),
    ]
