# Generated by Django 4.1.7 on 2023-03-21 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents_m', '0001_initial'),
        ('file', '0020_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='agents_m.profile', verbose_name="user's profile"),
        ),
        migrations.AlterField(
            model_name='rent',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents_m.profile', verbose_name='added to site by '),
        ),
        migrations.AlterField(
            model_name='sell',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agents_m.profile', verbose_name='added to site by '),
        ),
    ]
