# Generated by Django 4.1.7 on 2023-03-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0023_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sell', to='file.sell', verbose_name='file'),
        ),
    ]
