# Generated by Django 4.1.7 on 2023-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0028_rent_created_rent_pictures_rent_updated_sell_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
