# Generated by Django 4.1.7 on 2023-03-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0029_alter_rent_pictures_alter_sell_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='pictures',
        ),
    ]
