# Generated by Django 4.1.7 on 2023-03-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0030_remove_rent_pictures_remove_sell_pictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='SellImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('post', models.ManyToManyField(related_name='Images', to='file.sell', verbose_name='post')),
            ],
        ),
        migrations.CreateModel(
            name='RentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('post', models.ManyToManyField(related_name='Images', to='file.rent', verbose_name='post')),
            ],
        ),
    ]
