# Generated by Django 4.1.7 on 2023-04-05 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0032_sell_image1_sell_image2_sell_image3_sell_image4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_comments', to='file.rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_comments', to=settings.AUTH_USER_MODEL, verbose_name="user's profile")),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
