# Generated by Django 4.1.7 on 2023-04-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0033_rentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rent',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rent',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rent',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rent',
            name='image5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
