# Generated by Django 4.1.7 on 2023-07-01 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0042_alter_rent_bazdid_alter_rent_bedroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by '),
        ),
    ]
