# Generated by Django 4.1.7 on 2023-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0043_alter_rent_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price_rent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price_up',
            field=models.FloatField(),
        ),
    ]
