# Generated by Django 4.1.7 on 2023-07-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0045_alter_rent_price_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='type',
            new_name='property_type',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='type',
            new_name='property_type',
        ),
    ]
