# Generated by Django 4.1.7 on 2023-08-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0046_rename_type_rent_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='tenet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='tenet_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='tenet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='tenet_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='m2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
