# Generated by Django 4.1.7 on 2023-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0048_alter_sell_m2_alter_sell_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'برای اجاره'), ('UNACTIVE', 'اجاره داده شد'), ('CANCELED', 'برای اجاره نیست')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'برای فروش'), ('UNACTIVE', 'فروخته شد'), ('CANCELED', 'برای فروش نیست')], default='ACTIVE', max_length=12),
        ),
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
