# Generated by Django 4.1.7 on 2023-08-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0047_rent_divar_token_sell_divar_token'),
        ('file', '0050_alter_sell_added_by'),
    ]

    operations = [
    ]
