# Generated by Django 4.1.7 on 2023-11-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0014_buycustomer_status_rentcustomer_status"),
        ("file", "0053_alter_rent_tabdil"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="notified_customers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="customer.rentcustomer",
            ),
        ),
        migrations.AddField(
            model_name="sell",
            name="notified_customers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="customer.buycustomer",
            ),
        ),
    ]
