# Generated by Django 4.1.7 on 2023-11-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0014_buycustomer_status_rentcustomer_status"),
        ("file", "0055_remove_rent_notified_customers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="notified_customers",
            field=models.ManyToManyField(to="customer.rentcustomer"),
        ),
    ]
