# Generated by Django 4.1.7 on 2023-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0014_buycustomer_status_rentcustomer_status"),
        ("file", "0056_alter_rent_notified_customers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="notified_customers",
            field=models.ManyToManyField(
                blank=True, null=True, to="customer.rentcustomer"
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="notified_customers",
            field=models.ManyToManyField(
                blank=True, null=True, to="customer.buycustomer"
            ),
        ),
    ]
