# Generated by Django 5.0 on 2023-12-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0014_buycustomer_status_rentcustomer_status"),
        ("file", "0057_alter_rent_notified_customers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="notified_customers",
            field=models.ManyToManyField(blank=True, to="customer.rentcustomer"),
        ),
        migrations.AlterField(
            model_name="sell",
            name="notified_customers",
            field=models.ManyToManyField(blank=True, to="customer.buycustomer"),
        ),
    ]
