# Generated by Django 4.2 on 2024-03-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_buycustomer_status_rentcustomer_status'),
        ('file', '0057_alter_rent_notified_customers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='SellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='image5',
        ),
        migrations.AddField(
            model_name='rent',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sell',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='rent',
            name='notified_customers',
            field=models.ManyToManyField(blank=True, to='customer.rentcustomer'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='takhlie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='vahedha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='notified_customers',
            field=models.ManyToManyField(blank=True, to='customer.buycustomer'),
        ),
        migrations.DeleteModel(
            name='RentImages',
        ),
        migrations.DeleteModel(
            name='SellImages',
        ),
        migrations.AddField(
            model_name='sellimage',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='file.sell'),
        ),
        migrations.AddField(
            model_name='rentimage',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='file.rent'),
        ),
    ]
