# Generated by Django 4.2 on 2024-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0058_rentimage_sellimage_remove_sellimages_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
