# Generated by Django 4.2 on 2024-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0058_alter_rent_notified_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='sell',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
