# Generated by Django 4.2 on 2024-04-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0059_alter_rent_description_alter_sell_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='divar_token',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='divar_token',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
