# Generated by Django 5.0.4 on 2024-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0060_alter_rent_divar_token_alter_sell_divar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='bazdid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tabaghat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bazdid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='tabaghat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='takhlie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='vahedha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
