# Generated by Django 5.0.4 on 2024-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0061_alter_rent_bazdid_alter_rent_floor_alter_rent_m2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='lobbyMan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='lobbyMan_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='lobbyMan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='lobbyMan_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
