# Generated by Django 5.0.4 on 2024-07-15 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0062_rent_lobbyman_name_rent_lobbyman_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcomment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sellcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='rent',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 15, 16, 18, 24, 438630)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 15, 16, 18, 24, 438630)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RentComment',
        ),
        migrations.DeleteModel(
            name='SellComment',
        ),
    ]
