# Generated by Django 5.0.4 on 2024-07-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0063_remove_sellcomment_file_remove_sellcomment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='divar_token',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='divar_token',
        ),
        migrations.AddField(
            model_name='rent',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
