# Generated by Django 5.0.4 on 2024-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0064_remove_rent_divar_token_remove_sell_divar_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='rent',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
