# Generated by Django 5.0.4 on 2024-09-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0065_alter_rent_options_alter_sell_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='rent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
