# Generated by Django 5.0 on 2024-11-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0066_alter_rent_options_alter_sell_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='tags_manager',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='tag_manager',
        ),
    ]
