# Generated by Django 5.0 on 2024-12-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0067_remove_rent_tags_manager_remove_sell_tag_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='location',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='location',
            field=models.JSONField(null=True),
        ),
    ]
