# Generated by Django 5.0 on 2025-01-07 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0068_rent_location_sell_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='location',
        ),
        migrations.CreateModel(
            name='RentStaticLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(null=True)),
                ('image', models.ImageField(upload_to='locations-rent')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='file.rent')),
            ],
        ),
        migrations.CreateModel(
            name='SellStaticLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(null=True)),
                ('image', models.ImageField(upload_to='location-sell')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='file.sell')),
            ],
        ),
    ]
