# Generated by Django 5.0 on 2025-01-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0069_remove_rent_location_remove_sell_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentimage',
            name='image',
            field=models.ImageField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='file.rent', unique=True),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='file.sell', unique=True),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='image',
            field=models.ImageField(null=True, upload_to='location-sell'),
        ),
    ]
