# Generated by Django 5.0 on 2025-01-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0070_alter_rentimage_image_alter_rentstaticlocation_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='file.rent'),
        ),
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='image',
            field=models.ImageField(null=True, upload_to='locations-rent'),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='file.sell'),
        ),
    ]
