# Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0071_alter_rentstaticlocation_file_and_more'),
        ('utils', '0001_initial'),  
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='owner',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='utils.Person',
                verbose_name='Property Owner'
            ),
        ),
        migrations.AddField(
            model_name='rent',
            name='owner',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='utils.Person',
                verbose_name='Property Owner'
            ),
        ),
    ]
