# Generated by Django 5.0 on 2025-04-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0073_auto_20250422_1011'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.person', verbose_name='Customer Person'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.person', verbose_name='Customer Person'),
        ),
    ]
