# Generated by Django 5.0 on 2025-04-22 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0075_rent_owner_name_rent_owner_phone_sell_owner_name_and_more'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='lobbyMan_name',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='lobbyMan_phone',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='tenet_name',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='tenet_phone',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='lobbyMan_name',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='lobbyMan_phone',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='tenet_name',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='tenet_phone',
        ),
        migrations.AddField(
            model_name='rent',
            name='lobbyMan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent_lobbyMan_for', to='utils.person', verbose_name='lobby man Person'),
        ),
        migrations.AddField(
            model_name='rent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent_tenet_for', to='utils.person', verbose_name='tenant Person'),
        ),
        migrations.AddField(
            model_name='sell',
            name='lobbyMan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lobbyMan_for', to='utils.person', verbose_name='lobbyMan  Person'),
        ),
        migrations.AddField(
            model_name='sell',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenet_for', to='utils.person', verbose_name='tenat Person'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rents_as_owner', to='utils.person', verbose_name='Customer Person'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_properties', to='utils.person', verbose_name='Owner Person'),
        ),
    ]
