# Generated by Django 5.0 on 2025-04-28 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0076_remove_rent_lobbyman_name_remove_rent_lobbyman_phone_and_more'),
        ('utils', '0002_alter_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rents_as_owner', to='utils.person', verbose_name='owner Person'),
        ),
    ]
