# Generated by Django 5.0 on 2025-05-04 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0077_alter_rent_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tabdil',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
