# Generated by Django 5.0 on 2025-05-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0078_alter_rent_added_by_alter_rent_tabdil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'برای اجاره'), ('OLD', 'قدیمی'), ('UNACTIVE', 'اجاره داده شد'), ('CANCELED', 'برای اجاره نیست')], default='ACTIVE', max_length=12),
        ),
        migrations.AlterField(
            model_name='sell',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'برای فروش'), ('OLD', 'قدیمی'), ('UNACTIVE', 'فروخته شد'), ('CANCELED', 'برای فروش نیست')], default='ACTIVE', max_length=12),
        ),
    ]
