# Generated by Django 5.0 on 2025-06-04 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_buycustomer_customer_and_more'),
        ('file', '0079_alter_rent_status_alter_sell_status'),
        ('utils', '0002_alter_person_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-created'], 'verbose_name': 'فایل اجاره', 'verbose_name_plural': 'فایل\u200cهای اجاره'},
        ),
        migrations.AlterModelOptions(
            name='rentimage',
            options={'verbose_name': 'تصویر فایل اجاره', 'verbose_name_plural': 'تصاویر فایل\u200cهای اجاره'},
        ),
        migrations.AlterModelOptions(
            name='rentstaticlocation',
            options={'verbose_name': 'موقعیت ثابت فایل اجاره', 'verbose_name_plural': 'موقعیت\u200cهای ثابت فایل\u200cهای اجاره'},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['-created'], 'verbose_name': 'فایل فروش', 'verbose_name_plural': 'فایل\u200cهای فروش'},
        ),
        migrations.AlterModelOptions(
            name='sellimage',
            options={'verbose_name': 'تصویر فایل فروش', 'verbose_name_plural': 'تصاویر فایل\u200cهای فروش'},
        ),
        migrations.AlterModelOptions(
            name='sellstaticlocation',
            options={'verbose_name': 'موقعیت ثابت فایل فروش', 'verbose_name_plural': 'موقعیت\u200cهای ثابت فایل\u200cهای فروش'},
        ),
        migrations.AlterField(
            model_name='rent',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='اضافه شده توسط'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bazdid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شرایط بازدید'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ فایل'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='elevator',
            field=models.BooleanField(default=True, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='komod_divari',
            field=models.BooleanField(default=False, verbose_name='کمد دیواری'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='lobbyMan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lobbyman_for_rent_properties', to='utils.person', verbose_name='لابی\u200cمن'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='m2',
            field=models.IntegerField(blank=True, null=True, verbose_name='متراژ (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='notified_customers',
            field=models.ManyToManyField(blank=True, related_name='notified_rents', to='customer.rentcustomer', verbose_name='مشتریان مطلع شده'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_rent_properties', to='utils.person', verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='parking',
            field=models.BooleanField(default=True, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='parking_motor',
            field=models.BooleanField(default=False, verbose_name='پارکینگ موتور'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price_rent',
            field=models.FloatField(verbose_name='مبلغ اجاره ماهیانه'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price_up',
            field=models.IntegerField(verbose_name='مبلغ رهن (پیش پرداخت)'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='property_type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین و کلنگی'), ('S', 'اداری و تجاری'), ('H', 'خانه و ویلا')], default='A', max_length=1, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه منبع'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'برای اجاره'), ('OLD', 'قدیمی'), ('UNACTIVE', 'اجاره داده شد'), ('CANCELED', 'برای اجاره نیست')], default='ACTIVE', max_length=12, verbose_name='وضعیت اجاره'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='storage',
            field=models.BooleanField(default=True, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tabaghat',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tabdil',
            field=models.IntegerField(blank=True, null=True, verbose_name='قابلیت تبدیل (؟)'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='takhlie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت تخلیه'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_in_rent_properties', to='utils.person', verbose_name='مستاجر فعلی'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='vahedha',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='rentimage',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_rent', to='file.rent'),
        ),
        migrations.AlterField(
            model_name='rentimage',
            name='image',
            field=models.ImageField(null=True, upload_to='properties/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_rent', to='file.rent'),
        ),
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر نقشه'),
        ),
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='موقعیت (JSON)'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='اضافه شده توسط'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bazdid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شرایط بازدید'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ فایل'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='elevator',
            field=models.BooleanField(default=True, verbose_name='آسانسور'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='komod_divari',
            field=models.BooleanField(default=False, verbose_name='کمد دیواری'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='lobbyMan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lobbyman_for_sell_properties', to='utils.person', verbose_name='لابی\u200cمن'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='m2',
            field=models.IntegerField(blank=True, null=True, verbose_name='متراژ (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='notified_customers',
            field=models.ManyToManyField(blank=True, related_name='notified_sells', to='customer.buycustomer', verbose_name='مشتریان مطلع شده'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_sell_properties', to='utils.person', verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='parking',
            field=models.BooleanField(default=True, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='parking_motor',
            field=models.BooleanField(default=False, verbose_name='پارکینگ موتور'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.IntegerField(verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='property_type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین و کلنگی'), ('S', 'مغازه و غرفه'), ('H', 'خانه و ویلا')], default='A', max_length=1, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه منبع'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'برای فروش'), ('OLD', 'قدیمی'), ('UNACTIVE', 'فروخته شد'), ('CANCELED', 'برای فروش نیست')], default='ACTIVE', max_length=12, verbose_name='وضعیت فروش'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='storage',
            field=models.BooleanField(default=True, verbose_name='انباری'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='tabaghat',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='takhlie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت تخلیه'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_in_sell_properties', to='utils.person', verbose_name='ساکن فعلی'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='vahedha',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد واحدها'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='sellimage',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_sell', to='file.sell'),
        ),
        migrations.AlterField(
            model_name='sellimage',
            name='image',
            field=models.ImageField(null=True, upload_to='properties/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_sell', to='file.sell'),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر نقشه'),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='موقعیت (JSON)'),
        ),
    ]
