# Generated by Django 5.0 on 2025-06-04 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_alter_buycustomer_options_alter_rentcustomer_options_and_more'),
        ('file', '0080_alter_rent_options_alter_rentimage_options_and_more'),
        ('utils', '0002_alter_person_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='rentimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rentstaticlocation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sell',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='sellimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sellstaticlocation',
            options={},
        ),
        migrations.AlterField(
            model_name='rent',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bazdid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='elevator',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='komod_divari',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='lobbyMan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lobbyMan_for', to='utils.person', verbose_name='lobby man Person'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='notified_customers',
            field=models.ManyToManyField(blank=True, to='customer.rentcustomer'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_owned_properties', to='utils.person', verbose_name='Owner Person'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='parking',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='parking_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price_rent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price_up',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='property_type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین و کلنگی'), ('S', 'مغازه و غرفه'), ('H', 'خانه و ویلا')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='rent',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('OLD', 'قدیمی'), ('UNACTIVE', 'غیرفعال'), ('CANCELED', 'لغو شده')], default='ACTIVE', max_length=12),
        ),
        migrations.AlterField(
            model_name='rent',
            name='storage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tabaghat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tabdil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='takhlie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_tenant_for', to='utils.person', verbose_name='tenant Person'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='vahedha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentimage',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='file.rent'),
        ),
        migrations.AlterField(
            model_name='rentimage',
            name='image',
            field=models.ImageField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='file.rent'),
        ),
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='image',
            field=models.ImageField(null=True, upload_to='locations-rent'),
        ),
        migrations.AlterField(
            model_name='rentstaticlocation',
            name='location',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bazdid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='elevator',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='komod_divari',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sell',
            name='lobbyMan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_lobbyMan_for', to='utils.person', verbose_name='lobby man Person'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='m2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='notified_customers',
            field=models.ManyToManyField(blank=True, to='customer.buycustomer'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_owned_properties', to='utils.person', verbose_name='Owner Person'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='parking',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='parking_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='property_type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین و کلنگی'), ('S', 'مغازه و غرفه'), ('H', 'خانه و ویلا')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='sell',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('OLD', 'قدیمی'), ('UNACTIVE', 'غیرفعال'), ('CANCELED', 'لغو شده')], default='ACTIVE', max_length=12),
        ),
        migrations.AlterField(
            model_name='sell',
            name='storage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='tabaghat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='takhlie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_tenant_for', to='utils.person', verbose_name='tenant Person'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='vahedha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellimage',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='file.sell'),
        ),
        migrations.AlterField(
            model_name='sellimage',
            name='image',
            field=models.ImageField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='file.sell'),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='image',
            field=models.ImageField(null=True, upload_to='location-sell'),
        ),
        migrations.AlterField(
            model_name='sellstaticlocation',
            name='location',
            field=models.JSONField(null=True),
        ),
    ]
