# Generated by Django 4.1.7 on 2023-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=12)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RentCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=12)),
                ('up_budget', models.IntegerField()),
                ('rent_budget', models.IntegerField()),
            ],
        ),
    ]
