# Generated by Django 4.1.7 on 2023-08-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_rename_type_buycustomer_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'پیدا نکرده'), ('UNACTIVE', 'پیدا کرد'), ('CANCELED', 'منصرف شد')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'پیدا نکرده'), ('UNACTIVE', 'پیدا کرد'), ('CANCELED', 'منصرف شد')], default='ACTIVE', max_length=12),
        ),
    ]
