# Generated by Django 4.1.7 on 2023-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین'), ('S', 'مغازه')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین'), ('S', 'مغازه')], default='A', max_length=1),
        ),
    ]
