# Generated by Django 4.1.7 on 2023-04-14 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_buycustomer_type_rentcustomer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by '),
        ),
        migrations.AddField(
            model_name='buycustomer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buycustomer',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buycustomer',
            name='m2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buycustomer',
            name='parking',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buycustomer',
            name='storage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buycustomer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buycustomer',
            name='year',
            field=models.IntegerField(default=1380),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by '),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='m2',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='parking',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='storage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='year',
            field=models.IntegerField(default=1380),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین و کلنگی'), ('S', 'مغازه و غرفه'), ('H', 'خانه و ویلا')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین و کلنگی'), ('S', 'مغازه و غرفه'), ('H', 'خانه و ویلا')], default='A', max_length=1),
        ),
    ]
