# Generated by Django 4.1.7 on 2023-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_buycustomer_added_by_buycustomer_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycustomer',
            name='m2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='m2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
