# Generated by Django 4.1.7 on 2023-04-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_buycustomer_m2_alter_buycustomer_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buycustomer',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='rentcustomer',
            options={'ordering': ['-created']},
        ),
    ]
