# Generated by Django 4.1.7 on 2023-04-28 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_rentcomment_buycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycomment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_customer_comments', to='customer.buycustomer', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='buycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_customer_comments', to=settings.AUTH_USER_MODEL, verbose_name="user's profile"),
        ),
    ]
