# Generated by Django 4.1.7 on 2023-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_buycomment_file_alter_buycomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcustomer',
            name='rent_budget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='up_budget',
            field=models.FloatField(),
        ),
    ]
