# Generated by Django 4.1.7 on 2023-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_rentcustomer_rent_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcustomer',
            name='up_budget',
            field=models.IntegerField(),
        ),
    ]
