# Generated by Django 4.1.7 on 2023-07-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_rentcustomer_up_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='bedroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='bedroom',
            field=models.IntegerField(null=True),
        ),
    ]
