# Generated by Django 4.1.7 on 2023-07-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_buycustomer_bedroom_rentcustomer_bedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='vahedha',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='vahedha',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
