# Generated by Django 4.1.7 on 2023-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_buycustomer_vahedha_rentcustomer_vahedha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycustomer',
            name='vahedha',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='vahedha',
            field=models.IntegerField(null=True),
        ),
    ]
