# Generated by Django 4.1.7 on 2023-07-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_buycustomer_vahedha_alter_rentcustomer_vahedha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buycustomer',
            old_name='type',
            new_name='property_type',
        ),
        migrations.RenameField(
            model_name='rentcustomer',
            old_name='type',
            new_name='property_type',
        ),
    ]
