# Generated by Django 5.0.4 on 2024-05-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_buycustomer_status_rentcustomer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
