# Generated by Django 5.0.4 on 2024-07-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_buycustomer_description_rentcustomer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentcomment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='rentcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyComment',
        ),
        migrations.DeleteModel(
            name='RentComment',
        ),
    ]
