# Generated by Django 5.0.4 on 2024-07-15 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_buycustomer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcustomer',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 15, 16, 18, 24, 438630)),
            preserve_default=False,
        ),
    ]
