# Generated by Django 5.0.4 on 2024-07-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_rentcustomer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
