# Generated by Django 5.0.4 on 2024-09-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_buycustomer_source_id_rentcustomer_source_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buycustomer',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='rentcustomer',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
