# Generated by Django 5.0.4 on 2024-09-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_buycustomer_options_alter_rentcustomer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycustomer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
