# Generated by Django 5.0 on 2024-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_buycustomer_date_alter_rentcustomer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='parking_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='parking_motor',
            field=models.BooleanField(default=False),
        ),
    ]
