# Generated by Django 5.0 on 2025-04-22 06:25

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_buycustomer_parking_motor_rentcustomer_parking_motor'),
        ('utils', '0001_initial'),  
    ]

    operations = [
        migrations.AddField(
            model_name='buycustomer',
            name='customer',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='utils.Person',
            ),
        ),
        migrations.AddField(
            model_name='rentcustomer',
            name='customer',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='utils.Person',
            ),
        ),
    ]
