# Generated by Django 5.0 on 2025-04-22 06:25

from django.db import migrations
from customer.models import BuyCustomer, RentCustomer

def migrate_customer_data(apps, schema_editor):
    Person = apps.get_model('utils', 'Person')
    
    for obj in BuyCustomer.objects.all():
        person, created = Person.objects.get_or_create(
            last_name=obj.customer_name,
            phone_number=obj.customer_phone,
            defaults={'created_at': obj.created}
        )
        obj.customer_id = person.id  # Directly assign ID to avoid ORM issues
        obj.save(update_fields=['customer_id'])

    for obj in RentCustomer.objects.all():
        person, created = Person.objects.get_or_create(
            last_name=obj.customer_name,
            phone_number=obj.customer_phone,
            defaults={'created_at': obj.created}
        )
        obj.customer_id = person.id
        obj.save(update_fields=['customer_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_add_customer_foriegn_key'),
    ]

    operations = [
        migrations.RunPython(migrate_customer_data),
    ]
