# Generated by Django 5.0 on 2025-04-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_migrate_cusomter_data'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycustomer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
