# Generated by Django 5.0 on 2025-04-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_buycustomer_customer_rentcustomer_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycustomer',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='buycustomer',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='rentcustomer',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='rentcustomer',
            name='customer_phone',
        ),
    ]
