# Generated by Django 5.0 on 2025-04-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_remove_buycustomer_customer_name_and_more'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buycustomer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.person', verbose_name='Customer Person'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.person', verbose_name='Customer Person'),
        ),
    ]
