# Generated by Django 5.0 on 2025-06-04 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_buycustomer_customer_and_more'),
        ('utils', '0002_alter_person_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buycustomer',
            options={'ordering': ['-date'], 'verbose_name': 'مشتری خریدار', 'verbose_name_plural': 'مشتریان خریدار'},
        ),
        migrations.AlterModelOptions(
            name='rentcustomer',
            options={'ordering': ['-date'], 'verbose_name': 'مشتری مستاجر', 'verbose_name_plural': 'مشتریان مستاجر'},
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد خواب مورد نظر (حداقل)'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='budget',
            field=models.IntegerField(verbose_name='بودجه خرید'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy_requests', to='utils.person', verbose_name='مشتری خریدار'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات مشتری'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='نیاز به آسانسور'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='m2',
            field=models.IntegerField(blank=True, null=True, verbose_name='متراژ مورد نظر (حداقل)'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='parking',
            field=models.BooleanField(blank=True, null=True, verbose_name='نیاز به پارکینگ'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='parking_motor',
            field=models.BooleanField(default=False, verbose_name='نیاز به پارکینگ موتور'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='property_type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین و کلنگی'), ('S', 'مغازه و غرفه'), ('H', 'خانه و ویلا')], default='A', max_length=1, verbose_name='نوع ملک مورد نظر'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه منبع'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'در جستجو'), ('UNACTIVE', 'یافت شد'), ('CANCELED', 'منصرف شد')], default='ACTIVE', max_length=12, verbose_name='وضعیت درخواست خرید'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='storage',
            field=models.BooleanField(default=True, verbose_name='نیاز به انباری'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='vahedha',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر تعداد واحدها در ساختمان'),
        ),
        migrations.AlterField(
            model_name='buycustomer',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر سال ساخت'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد خواب مورد نظر (حداقل)'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent_requests', to='utils.person', verbose_name='مشتری مستاجر'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات مشتری'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='نیاز به آسانسور'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='m2',
            field=models.IntegerField(blank=True, null=True, verbose_name='متراژ مورد نظر (حداقل)'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='parking',
            field=models.BooleanField(blank=True, null=True, verbose_name='نیاز به پارکینگ'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='parking_motor',
            field=models.BooleanField(default=False, verbose_name='نیاز به پارکینگ موتور'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='property_type',
            field=models.CharField(choices=[('A', 'آپارتمان'), ('L', 'زمین و کلنگی'), ('S', 'مغازه و غرفه'), ('H', 'خانه و ویلا')], default='A', max_length=1, verbose_name='نوع ملک مورد نظر'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='rent_budget',
            field=models.FloatField(verbose_name='حداکثر اجاره ماهیانه'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه منبع'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'در جستجو'), ('UNACTIVE', 'یافت شد'), ('CANCELED', 'منصرف شد')], default='ACTIVE', max_length=12, verbose_name='وضعیت درخواست اجاره'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='storage',
            field=models.BooleanField(default=True, verbose_name='نیاز به انباری'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='up_budget',
            field=models.IntegerField(verbose_name='حداکثر رهن (پیش پرداخت)'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='vahedha',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر تعداد واحدها در ساختمان'),
        ),
        migrations.AlterField(
            model_name='rentcustomer',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر سال ساخت'),
        ),
    ]
