# Generated by Django 5.0 on 2025-04-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('F', 'خانم'), ('M', 'آقا')], max_length=1, null=True, verbose_name='gender')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, verbose_name='phone number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('last_contact', models.DateTimeField(blank=True, null=True, verbose_name='last contact')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Person',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
