# Generated by Django 5.0 on 2025-04-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default=989121234567, max_length=17, unique=True, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
