# Generated by Django 4.1.7 on 2023-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_m', '0003_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(choices=[('sell', 'فروش'), ('rent', 'اجاره')], default='sell', max_length=4),
        ),
    ]
