# Generated by Django 5.0.4 on 2024-05-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0014_buycustomer_status_rentcustomer_status'),
        ('file', '0061_alter_rent_bazdid_alter_rent_floor_alter_rent_m2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.rentcustomer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file.rent')),
            ],
        ),
        migrations.CreateModel(
            name='SellCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.buycustomer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file.sell')),
            ],
        ),
    ]
