# Generated by Django 5.0.4 on 2024-05-11 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcall',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentcall',
            name='subject',
            field=models.CharField(choices=[('P', 'پیگیری'), ('M', 'معرفی')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellcall',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellcall',
            name='subject',
            field=models.CharField(choices=[('P', 'پیگیری'), ('M', 'معرفی')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
