# Generated by Django 5.0.4 on 2024-10-19 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_buycustomer_date_alter_rentcustomer_date'),
        ('file', '0066_alter_rent_options_alter_sell_options_and_more'),
        ('logs', '0002_rentcall_added_by_rentcall_subject_sellcall_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('P', 'پس'), ('H', 'همراه')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.rentcustomer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file.rent')),
            ],
        ),
        migrations.CreateModel(
            name='SellTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('P', 'پس'), ('H', 'همراه')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='added to site by ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.buycustomer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='file.sell')),
            ],
        ),
    ]
