# Generated by Django 5.0 on 2024-12-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
