# Generated by Django 5.0 on 2025-04-28 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_smslog_phone_number'),
        ('utils', '0002_alter_person_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number')),
                ('call_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Call ID')),
                ('call_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('MISS', 'Missed')], default='IN', max_length=4, verbose_name='Call Type')),
                ('call_status', models.CharField(choices=[('COMP', 'Completed'), ('FAIL', 'Failed'), ('NOANS', 'No Answer'), ('BUSY', 'Busy')], default='COMP', max_length=5, verbose_name='Call Status')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='call_recordings/%Y/%m/%d/', verbose_name='Recording File')),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='Recording URL')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Handling Agent')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_recordings', to='utils.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Call Recording',
                'verbose_name_plural': 'Call Recordings',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time'], name='logs_call_start_t_5b4331_idx'), models.Index(fields=['person', 'start_time'], name='logs_call_person__84e6bb_idx')],
            },
        ),
    ]
