# Generated by Django 5.0 on 2025-04-28 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_call'),
        ('utils', '0002_alter_person_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='logs_call_start_t_5b4331_idx',
        ),
        migrations.RemoveField(
            model_name='call',
            name='notes',
        ),
        migrations.AddField(
            model_name='call',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_status',
            field=models.CharField(choices=[('COMP', 'Completed'), ('FAIL', 'Failed'), ('NOANS', 'No Answer'), ('BUSY', 'Busy')], default='COMP', max_length=5),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('MISS', 'Missed')], default='IN', max_length=4),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_recordings', to='utils.person'),
        ),
        migrations.AlterField(
            model_name='call',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='call',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['phone_number', 'start_time'], name='logs_call_phone_n_cef388_idx'),
        ),
    ]
