# Generated by Django 5.0 on 2025-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_call_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='recording_transcription',
            field=models.TextField(blank=True),
        ),
    ]
