# Generated by Django 5.0 on 2025-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_call_recording_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_transcript_correct',
            field=models.BooleanField(default=False),
        ),
    ]
