# Generated by Django 5.0 on 2025-06-04 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_alter_buycustomer_options_alter_rentcustomer_options_and_more'),
        ('file', '0081_alter_rent_options_alter_rentimage_options_and_more'),
        ('logs', '0009_call_is_transcript_correct'),
        ('utils', '0002_alter_person_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-start_time'], 'verbose_name': 'لاگ تماس تلفنی', 'verbose_name_plural': 'لاگ\u200cهای تماس تلفنی'},
        ),
        migrations.AlterModelOptions(
            name='rentcall',
            options={'verbose_name': 'لاگ تماس اجاره', 'verbose_name_plural': 'لاگ\u200cهای تماس اجاره'},
        ),
        migrations.AlterModelOptions(
            name='renttour',
            options={'verbose_name': 'بازدید/مراجعه فایل اجاره', 'verbose_name_plural': 'بازدیدها/مراجعات فایل\u200cهای اجاره'},
        ),
        migrations.AlterModelOptions(
            name='sellcall',
            options={'verbose_name': 'لاگ تماس فروش', 'verbose_name_plural': 'لاگ\u200cهای تماس فروش'},
        ),
        migrations.AlterModelOptions(
            name='selltour',
            options={'verbose_name': 'بازدید/مراجعه فایل فروش', 'verbose_name_plural': 'بازدیدها/مراجعات فایل\u200cهای فروش'},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ پیامک', 'verbose_name_plural': 'لاگ\u200cهای پیامک'},
        ),
        migrations.RemoveField(
            model_name='rentcall',
            name='created',
        ),
        migrations.RemoveField(
            model_name='rentcall',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='renttour',
            name='created',
        ),
        migrations.RemoveField(
            model_name='renttour',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='sellcall',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sellcall',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='selltour',
            name='created',
        ),
        migrations.RemoveField(
            model_name='selltour',
            name='updated',
        ),
        migrations.AddField(
            model_name='rentcall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentcall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AddField(
            model_name='renttour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renttour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AddField(
            model_name='sellcall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellcall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AddField(
            model_name='selltour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selltour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='call',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اپراتور پاسخگو'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه تماس'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_status',
            field=models.CharField(choices=[('COMP', 'موفق'), ('FAIL', 'ناموفق'), ('NOANS', 'بدون پاسخ'), ('BUSY', 'مشغول')], default='COMP', max_length=5, verbose_name='وضعیت تماس'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('IN', 'ورودی'), ('OUT', 'خروجی'), ('MISS', 'از دست رفته')], default='IN', max_length=4, verbose_name='نوع تماس'),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد رکورد'),
        ),
        migrations.AlterField(
            model_name='call',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)'),
        ),
        migrations.AlterField(
            model_name='call',
            name='end_time',
            field=models.DateTimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='call',
            name='is_transcript_correct',
            field=models.BooleanField(default=False, verbose_name='صحت متن پیاده\u200cسازی شده'),
        ),
        migrations.AlterField(
            model_name='call',
            name='location',
            field=models.JSONField(blank=True, null=True, verbose_name='موقعیت مکانی (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='call',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='utils.person', verbose_name='شخص مرتبط'),
        ),
        migrations.AlterField(
            model_name='call',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='call',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/%Y/%m/%d/', verbose_name='فایل ضبط شده'),
        ),
        migrations.AlterField(
            model_name='call',
            name='recording_transcription',
            field=models.TextField(blank=True, verbose_name='متن پیاده\u200cسازی شده'),
        ),
        migrations.AlterField(
            model_name='call',
            name='recording_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس فایل ضبط شده'),
        ),
        migrations.AlterField(
            model_name='call',
            name='start_time',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='call',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی رکورد'),
        ),
        migrations.AlterField(
            model_name='rentcall',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
        migrations.AlterField(
            model_name='rentcall',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='call_logs_rent_customer', to='customer.rentcustomer', verbose_name='مشتری مستاجر'),
        ),
        migrations.AlterField(
            model_name='rentcall',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='rentcall',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='call_logs_rent', to='file.rent', verbose_name='فایل اجاره مرتبط'),
        ),
        migrations.AlterField(
            model_name='rentcall',
            name='subject',
            field=models.CharField(choices=[('P', 'پیگیری'), ('M', 'معرفی فایل'), ('O', 'سایر موارد')], max_length=2, verbose_name='موضوع تماس'),
        ),
        migrations.AlterField(
            model_name='renttour',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
        migrations.AlterField(
            model_name='renttour',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_logs_rent_customer', to='customer.rentcustomer', verbose_name='مشتری مستاجر'),
        ),
        migrations.AlterField(
            model_name='renttour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='renttour',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_logs_rent', to='file.rent', verbose_name='فایل اجاره مرتبط'),
        ),
        migrations.AlterField(
            model_name='renttour',
            name='tour_type',
            field=models.CharField(choices=[('P', 'بازدید پس از معرفی (پس فایل)'), ('H', 'بازدید به همراه مشتری'), ('I', 'مراجعه اولیه مشتری')], max_length=2, verbose_name='نوع بازدید/مراجعه'),
        ),
        migrations.AlterField(
            model_name='sellcall',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
        migrations.AlterField(
            model_name='sellcall',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='call_logs_buy', to='customer.buycustomer', verbose_name='مشتری خریدار'),
        ),
        migrations.AlterField(
            model_name='sellcall',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='sellcall',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='call_logs_sell', to='file.sell', verbose_name='فایل فروش مرتبط'),
        ),
        migrations.AlterField(
            model_name='sellcall',
            name='subject',
            field=models.CharField(choices=[('P', 'پیگیری'), ('M', 'معرفی فایل'), ('O', 'سایر موارد')], max_length=2, verbose_name='موضوع تماس'),
        ),
        migrations.AlterField(
            model_name='selltour',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
        migrations.AlterField(
            model_name='selltour',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_logs_buy', to='customer.buycustomer', verbose_name='مشتری خریدار'),
        ),
        migrations.AlterField(
            model_name='selltour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='selltour',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_logs_sell', to='file.sell', verbose_name='فایل فروش مرتبط'),
        ),
        migrations.AlterField(
            model_name='selltour',
            name='tour_type',
            field=models.CharField(choices=[('P', 'بازدید پس از معرفی (پس فایل)'), ('H', 'بازدید به همراه مشتری'), ('I', 'مراجعه اولیه مشتری')], max_length=2, verbose_name='نوع بازدید/مراجعه'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال/ثبت'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='message',
            field=models.TextField(verbose_name='متن پیامک'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='شماره تلفن گیرنده'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.BooleanField(verbose_name='وضعیت ارسال (موفقیت)'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='task_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='شناسه تسک'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_id'], name='logs_call_call_id_974f00_idx'),
        ),
    ]
