# Generated by Django 5.0 on 2025-06-17 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_alter_call_options_alter_rentcall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renttour',
            name='tour_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='تاریخ انجام بازدید/مراجعه', verbose_name='تاریخ بازدید'),
        ),
        migrations.AddField(
            model_name='selltour',
            name='tour_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='تاریخ انجام بازدید/مراجعه', verbose_name='تاریخ بازدید'),
        ),
    ]
