# Generated by Django 5.0 on 2025-06-17 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_renttour_tour_date_selltour_tour_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renttour',
            name='tour_date',
        ),
        migrations.RemoveField(
            model_name='selltour',
            name='tour_date',
        ),
        migrations.AddField(
            model_name='renttour',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selltour',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
